# Autostart
#exec-once = wayle panel start &
exec-once = wl-clip-persist --clipboard regular --reconnect-tries 0
exec-once = wl-paste --type text --watch cliphist store
exec-once = waybar
exec-once = awww-daemon &
exec-once = awww img ~/Escritorio/wallpapers/0008.jpg
exec-once = swayidle -w lock 'swaylock' timeout 300 'swaylock' before-sleep 'swaylock' &
