# Autostart
exec_once = wl-clip-persist --clipboard regular --reconnect-tries 0
exec_once = wl-paste --type text --watch cliphist store
exec_once = waybar
exec_once = awww-daemon &
exec_once = awww img ~/Escritorio/wallpapers/0008.jpg
exec_once = swayidle -w lock 'swaylock' timeout 300 'swaylock' before-sleep 'swaylock' &
